# Generated by Django 3.1.6 on 2021-02-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20210228_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Admin', 'Admin'), ('Employee', 'Employee'), ('HR', 'HR')], default='Employee', max_length=15),
        ),
    ]
