# Generated by Django 3.1.6 on 2021-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auto_20210307_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_No',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
