# Generated by Django 3.1.6 on 2021-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_auto_20210307_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_No',
            field=models.IntegerField(null=True),
        ),
    ]
