# Generated by Django 3.1.6 on 2021-03-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='contact_No',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
