# Generated by Django 3.1.6 on 2021-03-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveapplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_No', models.IntegerField()),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('leaveType', models.CharField(blank=True, max_length=30, null=True)),
                ('totalhours', models.CharField(blank=True, max_length=10, null=True)),
                ('reasons', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.userprofile')),
            ],
        ),
    ]
