# Generated by Django 3.1.6 on 2021-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_assignprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
