# Generated by Django 3.1.7 on 2021-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_leaveapplication_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='contact_No',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='totalhours',
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leaveType',
            field=models.CharField(default='Sick Leave', max_length=30),
            preserve_default=False,
        ),
    ]
