# Generated by Django 3.1.7 on 2021-04-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_leaveapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.CharField(default='LA62770738545', max_length=30),
        ),
    ]
