# Generated by Django 3.1.7 on 2021-04-16 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0027_leaveapplication_leave_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='contact_No',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='name',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='in_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='out_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present')], default='Present', max_length=15),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.CharField(default='LA83335487291', max_length=30),
        ),
    ]
