# Generated by Django 3.1.7 on 2021-04-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_auto_20210417_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignprojects',
            name='assignto',
        ),
        migrations.AddField(
            model_name='assignprojects',
            name='description',
            field=models.TextField(default='Send Email to Mr. Satish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignprojects',
            name='pname',
            field=models.CharField(default='Send Mail', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.CharField(default='LA22651497847', max_length=30),
        ),
    ]
