# Generated by Django 3.1.7 on 2021-04-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0030_auto_20210417_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.CharField(default='LA61939974570', max_length=30),
        ),
    ]
