# Generated by Django 3.1.7 on 2021-04-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0031_auto_20210417_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='leave_id',
            field=models.CharField(default='IN44520335098', max_length=30),
        ),
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.CharField(default='LA39697035421', max_length=30),
        ),
    ]
