# Generated by Django 3.1.7 on 2021-04-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0032_auto_20210417_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='leave_id',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_id',
            field=models.CharField(default='IN86877494857', max_length=30),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.CharField(default='LA47686397237', max_length=30),
        ),
    ]
