# Generated by Django 3.1.7 on 2021-04-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_auto_20210417_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignprojects',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='Admin.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignprojects',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_id',
            field=models.CharField(default='IN40853423049', max_length=30),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_id',
            field=models.CharField(default='LA41544915767', max_length=30),
        ),
    ]
